//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classless.Encoder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Classless.Encoder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Alphabet cannot be null..
        /// </summary>
        internal static string alphabetCantBeNull {
            get {
                return ResourceManager.GetString("alphabetCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Alphabet does not contain enough characters..
        /// </summary>
        internal static string alphabetTooShort {
            get {
                return ResourceManager.GetString("alphabetTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A decoder has not been implemented for this encoder..
        /// </summary>
        internal static string decoderNotImplemented {
            get {
                return ResourceManager.GetString("decoderNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A character was encountered during decoding that is not part of the algorithm&apos;s alphabet..
        /// </summary>
        internal static string illegalCharacter {
            get {
                return ResourceManager.GetString("illegalCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BlockSize must be greater than zero..
        /// </summary>
        internal static string invalidBlockSize {
            get {
                return ResourceManager.GetString("invalidBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BufferSize must be greater than zero..
        /// </summary>
        internal static string invalidBufferSize {
            get {
                return ResourceManager.GetString("invalidBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are leftover bits in the buffer. Not enough characters have been decoded..
        /// </summary>
        internal static string leftoverDecodedBits {
            get {
                return ResourceManager.GetString("leftoverDecodedBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Stream cannot be null..
        /// </summary>
        internal static string streamCantBeNull {
            get {
                return ResourceManager.GetString("streamCantBeNull", resourceCulture);
            }
        }
    }
}
